### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by SocketSomeone** [necordjs/necord.org#1]
- [x] Add articles that are in progress
- [x] Improve code blocks (exposed lacks of the imports)
- [x] Own website (Cloudflare Pages hosting)
- [x] Migrate from Wiki to Docusaurus
- [x] Support Algolia
- [x] SEO
- [x] Footer (Optional)
- [x] PWA (Optional)
- [x] Change colors (Algolia, [Contrast](https://docusaurus.io/docs/next/styling-layout#styling-your-site-with-infima))
- [x] Update Readme

**Need to document:**
- [x] Validation, Transformation
- [x]  Autocomplete
- [x] Permissions
- [x] Modals
- [x] Dynamic matching
- [x] Sharding

**Comment by wolffparkinson** [comment]
[This completes](https://github.com/necordjs/necord.org/pull/113) :
- Modals
- Dynamic matching

**Comment by wolffparkinson** [comment]
Cooldown using redis ? in-memory cache ?

**Comment by SocketSomeone** [comment]
> Cooldown using redis ? in-memory cache ?

I think in-memory

**Comment by wolffparkinson** [comment]
ok I will give it try on weekend.
maybe a adapter ?

**Comment by SocketSomeone** [comment]
> ok I will give it try on weekend. maybe a adapter ?

you could try, i will review hmm
